name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - uses: psf/black@stable
        with:
          options: "--check --verbose"

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install poetry
      - name: Install project and its dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest --cache-clear tests

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install poetry
      - name: Install project and its dependencies
        run: poetry install
      - name: Build coverage file
        run: poetry run pytest --cache-clear --cov src/urtypes --cov-report xml tests
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v2
